layout: stacked # sidebar | stacked
style: light # dark | light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
#   sort_by: stars
#   # sort_by options:
#   #   - pushed
#   #   - stars
#   limit: 9
  include:
    forks: false  
  exclude:
    archived: true
#     projects:
#     - image-searcher
#     - contentful-sync

social_media:
  linkedin: kakkoyun
  medium: '@kakkoyun'
  stackoverflow: 1113525
  twitter: kkakkoyun
  # youtube: your_username
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  medium: kakkoyun
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: http://kakkoyun.me
  # youtube: your_username

# topics:
#   - name: Go
#     web_url: https://github.com/topics/go
#     image_url: https://avatars1.githubusercontent.com/u/4314092?s=200&v=4

#   - name: Kubernetes
#     web_url: https://github.com/topics/kubernetes
#     image_url: https://raw.githubusercontent.com/github/explore/46beb428f6ba77f5de33ba7633402379aba5d92d/topics/kubernetes/kubernetes.png

#   # - name: Monitoring
#     # web_url: https://github.com/topics/monitoring
#     # image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/ruby/ruby.png

#   - name: Prometheus
#     web_url: https://github.com/topics/prometheus
#     image_url: https://avatars1.githubusercontent.com/u/3380462

#   - name: Thanos
#     web_url: https://github.com/topics/thanos
#     image_url: https://avatars3.githubusercontent.com/u/49725059

#   - name: Docker
#     web_url: https://github.com/topics/docker
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/docker/docker.png

#   - name: Elixir
#     web_url: https://github.com/topics/elixir
#     image_url: https://avatars2.githubusercontent.com/u/1481354?s=200&v=4
